import './style.css';
import {fields,type Expense,type Field} from '../src/record';
type Receipt={id:string;split:string;condition:string;image:string;engine:string;latencyMs:number;record:Expense};
const app=document.querySelector<HTMLDivElement>('#app')!;
const receipts:Receipt[]=await fetch('/demo/receipts.json').then(r=>r.json());const report=await fetch('/demo/report.json').then(r=>r.json());
let active=receipts[0],selected='total';let reviewed=new Map<string,string|null>();
const esc=(s:unknown)=>String(s??'Not found').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function render(){const rows=fields(active.record),current=rows.find(([k])=>k===selected)?.[1]??rows[0][1];const needs=rows.filter(([k,f])=>f.review&&!reviewed.has(k)).length;
 app.innerHTML=`<header><a class="brand" href="/">▧ <span>SayIt<span class="light">BillIt</span></span></a><nav><a href="#workspace">Workspace</a><a href="#results">Pilot results</a><a href="https://github.com/imranrkhan13/sayit-billit">Source ↗</a></nav><span class="pilot">PUBLIC PILOT · 01</span></header>
 <main><div class="intro"><div><p class="eyebrow">LESS PAPERWORK. MORE CERTAINTY.</p><h1>Every number.<br><span>A source to back it up.</span></h1><p>Turn a receipt into an expense you can check.<br>Select any field to see exactly where it came from.</p></div><div class="budget"><span>THIS SESSION</span><strong>$0.0000</strong><small>0 API tokens · cached offline results</small><div class="dotline">● No paid calls enabled</div></div></div>
 <div class="notice"><strong>An honest first slice.</strong> These are real Tesseract results on self-made receipts. Interfaze integration is awaiting a free API key. No simulated model outputs.</div>
 <section id="workspace"><div class="toolbar"><div><span class="step">01</span> Choose a receipt</div><select aria-label="Receipt">${receipts.map(r=>`<option value="${r.id}" ${r.id===active.id?'selected':''}>${r.id} · ${r.condition} · ${r.split}</option>`).join('')}</select><label class="upload">Open local image<input type="file" accept="image/png,image/jpeg" id="upload"></label></div>
 <div class="workspace"><article class="source"><div class="panelhead"><h2>Original receipt</h2><span>SELF-MADE · CC0</span></div><div class="imagewrap"><img id="receipt" src="${esc(active.image)}" alt="Original fictional ${esc(active.condition)} receipt"><svg viewBox="0 0 640 650" aria-label="Selected field evidence">${current.evidence.filter(e=>e.box).map(e=>`<rect x="${e.box![0]}" y="${e.box![1]}" width="${e.box![2]}" height="${e.box![3]}"/>`).join('')}</svg></div><div class="sourcefoot">↗ Linked directly to OCR coordinates <span>${Math.round(active.latencyMs)} ms</span></div></article>
 <article class="record"><div class="panelhead"><h2>Expense record</h2><span class="tag">${needs} TO REVIEW</span></div><p class="engine">${esc(active.engine)} <span>expense.v1</span></p><div class="fields">${rows.map(([k,f])=>`<button class="field ${k===selected?'selected':''}" data-field="${k}"><span class="fieldname">${esc(k.replace(/items\.(\d+)\.(.*)/,(_,n,v)=>`Item ${Number(n)+1} · ${v}`))}</span><strong>${esc(reviewed.has(k)?reviewed.get(k):f.value)}</strong><span class="confidence ${f.review?'amber':''}">${reviewed.has(k)?'Reviewed':f.value===null?'Missing':Math.round(f.score*100)+'%'}</span><span class="arrow">↗</span></button>`).join('')}</div><div class="evidence"><p class="eyebrow">EVIDENCE / ${esc(selected.toUpperCase())}</p><blockquote>${current.evidence.length?current.evidence.map(e=>esc(e.quote)).join(' · '):'No verified source. Do not guess.'}</blockquote><p>${esc(current.reasons.join(' · ')||'Above the dev-tuned baseline threshold. Still verify before bookkeeping.')}</p><label>Verify or correct this value<input id="correction" value="${esc(reviewed.get(selected)??current.value??'')}" placeholder="Enter only a value you can verify"></label><button id="confirm" class="secondary">Mark reviewed</button> <button id="unknown" class="secondary">Confirm unknown</button></div><div class="export"><span>${needs?'Review flagged fields before final export.':'No pending flags. Verify before bookkeeping.'}</span><button id="export" ${needs?'disabled':''}>Export expense ↓</button></div></article></div></section>
 <section id="results" class="results"><div><p class="eyebrow">MEASURED, NOT MARKETED</p><h2>A tiny pilot. Visible limitations.</h2><p>3 development receipts. 6 held-out receipts. Original synthetic layouts, not real-world financial documents. No winner declared.</p></div><div class="metrics"><div><strong>${(report.fieldAccuracy*100).toFixed(1)}%</strong><span>Baseline field accuracy</span></div><div><strong>${report.errorFlagRecall===null?'N/A':(report.errorFlagRecall*100).toFixed(0)+'%'}</strong><span>Errors flagged for review</span></div><div><strong>Not run</strong><span>Interfaze / voice evaluation</span></div></div><details><summary>Method, confidence & limitations</summary><p>Exact field match, ordered items, null abstentions included in accuracy. Threshold ${(report.config.threshold*100).toFixed(0)}% tuned on dev only. OCR scores are recognition scores, not calibrated correctness probabilities. ${report.confidentWrong.length} high-score wrong fields; ${report.acceptedWrong.length} accepted wrong fields. Flag precision: ${report.flagPrecision===null?'N/A':(report.flagPrecision*100).toFixed(1)+'%'}.</p><p>The public demo replays immutable baseline predictions. Local image previews do not run extraction. Run the local CLI with confirmed free Interfaze credits for new extraction; private receipts and API keys never belong in the public repository.</p><a href="/demo/report.json">Download full evaluation JSON ↗</a></details></section><footer><span>SayIt BillIt · Evidence before confidence.</span><span>MIT code / CC0 sample data</span></footer></main>`;
 app.querySelector('select')!.addEventListener('change',e=>{active=receipts.find(r=>r.id===(e.target as HTMLSelectElement).value)!;selected='total';reviewed=new Map();render();});
 app.querySelectorAll<HTMLButtonElement>('[data-field]').forEach(b=>b.onclick=()=>{selected=b.dataset.field!;render();});
 app.querySelector<HTMLButtonElement>('#confirm')!.onclick=()=>{const value=app.querySelector<HTMLInputElement>('#correction')!.value.trim();if(!value)return;reviewed.set(selected,value);render();};
 app.querySelector<HTMLButtonElement>('#unknown')!.onclick=()=>{reviewed.set(selected,null);render();};
 app.querySelector<HTMLButtonElement>('#export')!.onclick=()=>{const output={...active,reviewedAt:new Date().toISOString(),humanCorrections:Object.fromEntries(reviewed),status:'flags-resolved',note:'Original machine predictions preserved; corrections stored separately.'};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(output,null,2)],{type:'application/json'}));a.download=active.id+'.expense.json';a.click();URL.revokeObjectURL(a.href);};
 app.querySelector<HTMLInputElement>('#upload')!.onchange=e=>{const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;if(f.size>20_000_000){alert('Maximum file size: 20 MB');return;}const url=URL.createObjectURL(f);const modal=document.createElement('dialog');modal.innerHTML=`<h2>Local preview only</h2><p>Your image stays in this browser. New extraction requires the local Interfaze runner and confirmed free credits.</p><img src="${url}" alt="Your local receipt preview" style="max-width:100%;max-height:50vh"><p><code>npm run extract -- /path/to/receipt.png</code></p><button>Close preview</button>`;document.body.append(modal);modal.querySelector('button')!.onclick=()=>modal.close();modal.onclose=()=>{URL.revokeObjectURL(url);modal.remove();};modal.showModal();};
}
render();
